apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: docker.io/${{ secrets.REGISTRY_USERNAME }}/hello-service:latest
        ports:
        - containerPort: 80
